name: Web Data Collector Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      id: checkout  
      uses: actions/checkout@v3

    - name: Set up repository path
      run: echo "REPO_PATH=${{github.workspace}}" >> $GITHUB_ENV 

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r $REPO_PATH/requirements.txt 
        
    - name: Print current working directory before running script
      run: |
        echo "Current working directory before running the script:"
        pwd
        echo "List of files:"
        ls
        
    - name: Run Web Data Collector Tests
      run: |
        python ./tests_/common_/runners_/htmlRunners_/regressionRunner.py 

    - name: Upload HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: web-data-collector-report
        path: $REPO_PATH/reports_/report_*.html  
