name: Web Data Collector Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PATH_TRIGGER: 1  

    steps:
    - name: Checkout code
      id: checkout  
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
  
    - name: Install Firefox
      run: |
        sudo apt-get update && sudo apt-get install -y firefox
        firefox --version

    - name: Create and Activate Virtual Environment
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager
        pip install -r ./requirements.txt

    - name: Print current working directory before running script
      run: |
        echo "Current working directory before running the script:"
        pwd
        echo "List of files:"
        ls
    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV
        echo "Python path set to: ${{ github.workspace }}"
        
    - name: Run Christmas Tree Script
      run: |
        source venv/bin/activate
        python ./tests_/common_/runners_/htmlRunners_/regressionRunner.py

    - name: Upload HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: web-data-collector-report
        path: ./reports_/report_*.html  
