name: Web Data Collector Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PATH_TRIGGER: 1  
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up environment and run tests
      run: |
        # Set up Python
        sudo apt-get update
        sudo apt-get install -y python3 python3-venv python3-pip firefox
        python3 --version
        firefox --version
        
        # Create and activate virtual environment
        python3 -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager
        pip install -r ./requirements.txt
              
        # Set PYTHONPATH
        echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV
        source $GITHUB_ENV
        echo "Python path set to: ${{ github.workspace }}"
        
        # Print current working directory and list files
        echo "Current working directory before running the script:"
        pwd
        echo "List of files:"
        ls
        
        # Run Christmas Tree Script
        python ./tests_/common_/runners_/htmlRunners_/regressionRunner.py
  
    - name: Upload HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: web-data-collector-report
        path: ./reports_/report_*.html  
